$mod = SUPER                # o MOD4, ALT, lo que prefieras

# 2) Carga hyprpm al iniciar para que traiga los plugins
exec-once = hyprpm reload -n

# 3) Opciones generales
general {
    layout = hy3            # usa el layout de hy3
}

