# Configuración básica funcional de Alacritty

[window]
decorations = "none"
dynamic_title = false
startup_mode = "Windowed"
padding = { x = 10, y = 10 }
opacity = 0.9

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
builtin_box_drawing = true
size = 12.5

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Beam"

[scrolling]
history = 1000
multiplier = 3

[general]
import = [
    "./themes/themes/everforest_dark.toml"
]


